  modules:
    kits:
      enabled: true
    temporaryblocks:
      enabled: true
    spawn:
      enabled: true
    claims:
      enabled: true
    scoreboard:
      enabled: true
    reboot:
      enabled: true