# ... (otras configuraciones de módulos)

modules:
  kits:
    enabled: true
  temporaryblocks:
    enabled: true
  spawn:
    enabled: true
  claims:
    enabled: true
  scoreboard:
    enabled: true
  deathmessages:
    enabled: true
  autorespawn:
    enabled: true
  economy:
    enabled: true